app.name=EMS
# DB connection
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/employee_db
db.username=postgres
db.password=postgrace

# Hibernate settings
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update